const LOCAL_STORAGE_LOGGED_IN_USER_DATA = "currentUser";
const LOCAL_STORAGE_JWT_TOKEN = "token";
const LOCAL_STORAGE_IS_USER_FROM_REGISTER = "isUserFromRegister";

export {
    LOCAL_STORAGE_LOGGED_IN_USER_DATA,
    LOCAL_STORAGE_JWT_TOKEN,
    LOCAL_STORAGE_IS_USER_FROM_REGISTER
}
